In [1]:
%pip install nptyping beartype --upgrade --force

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.2 kB 330.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 292.6 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 326.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
   - ------------------------------------- 41.0/819.1 kB 653.6 kB/s eta 0:00:02
   ---- ---------------------------------- 92.2/819.1 kB 871.5 kB/s eta 0:00:01
   ----- -------------------------------- 112.6/819.1 kB 819.2 kB/s eta 0:00:01
   ------ ------------------------------- 143.4/819.1 kB 847.9 kB/s eta 0:00:01
   --------- ---------------------------- 194.6/819.1 kB 908.0 kB/s eta 0:00:01

# Scalar value

In [3]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object () = 0 -Denormalized
display(a.dtype) # prints the dtype of the object
display(type(a)) 
display(a.ndim) # prints the number of dimensions
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object

array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

# Vector values

In [2]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [1 2 3 4]'

'objec shape (4,)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'4'

# Matrix

In [7]:
import numpy as np

data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'objec shape (3, 4)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 12'

'4'

# Numpy with NDArray typing support

In [3]:
from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)
print(data + 5) # addition operation

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [7]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]

[i + 5 for i in d1] 

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [8]:
%%time

data : NDArray[Shape["10"], Any] = np.arange(1,10000000)

data + 5 # addition operation

CPU times: total: 46.9 ms
Wall time: 41.1 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [9]:
%%time
data : list[int] = list(range(1,10000000))

[i + 5  for i in data]# addition operation

CPU times: total: 1.05 s
Wall time: 1.07 s


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [12]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000 # normal python list
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [18]:
ndata : NDArray[Shape["20"],Any] = np.arange(1,21)

print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d functions

In [4]:
from nptyping import Bool
statebank : NDArray[Shape['10'],Any] = np.array([1,5,8,10])

select : NDArray[Shape['10'],Bool] = np.array([True, False, False, True])

statebank[select]

array([ 1, 10])

In [22]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])

statebank % 2 == 0

array([False, False,  True,  True])

In [23]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])

state_bank[statebank % 2 == 0]

array([ 8, 10])

In [10]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])

ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100, 20) #here 20 is size

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([ 1, 42, 82, 55, 20, 40, 34, 17, 90, 14, 42, 55, 31, 72, 89, 28, 49,
        4, 88, 24])

In [11]:
display(state_bank)
display(ubl_bank)

np.in1d(state_bank,ubl_bank) #It will show common values in both array

array([ 1,  7,  8, 10])

array([ 1, 42, 82, 55, 20, 40, 34, 17, 90, 14, 42, 55, 31, 72, 89, 28, 49,
        4, 88, 24])

array([ True, False, False, False])

In [12]:
display(state_bank)
display(ubl_bank)

state_bank[np.in1d(state_bank,ubl_bank)]

array([ 1,  7,  8, 10])

array([ 1, 42, 82, 55, 20, 40, 34, 17, 90, 14, 42, 55, 31, 72, 89, 28, 49,
        4, 88, 24])

array([1])

In [13]:
np.intersect1d(state_bank,ubl_bank)

array([1])

In [15]:
x : NDArray[Shape["5"],Any] = np.array([1,3,4,5,7])
y : NDArray[Shape["5"],Any] = np.array([6,3,2,5,100])

display(x)
display(y)
np.where(x > y,x,y) 

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

In [16]:
a : NDArray[Shape["Size,Size"], Any] = np.array([[1,2,3],
                                                 [4,5,6]])

print(a)

b : NDArray[Shape["Size,Size"], Any] = np.array([[7,8],
                                                 [10,11]])

print(b)
c : NDArray[Shape["Size,Size"], Any] = np.array([["A"],
                                                 ["B"]])

print(c)


[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [10 11]]
[['A']
 ['B']]


In [21]:
a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [23]:
np.who()

Name            Shape            Bytes            Type

data            10               40               int32
a               2 x 1            8                str32
b               2 x 2            16               int32
c               2 x 1            8                str32

Upper bound on total bytes  =       72


# Create any dimension array

In [6]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a) 

b :  NDArray[Shape["Size"],Any] = np.arange(1,10)
print(b)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [17]:
a : NDArray[Shape["Size,Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)

b : NDArray[Shape["Size,Size"],Any] = np.arange(5*3).reshape(5,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [9]:
a : NDArray[Shape["Size,Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)

print('=======')

b : NDArray[Shape["Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(b)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [11]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[::2,::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [21]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)

a % 2 == 0

array([[[ True, False],
        [ True, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [ True, False]]])

In [20]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)

a[a % 2 == 0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.asarray([1,2,3])

array([1, 2, 3])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)

a[[0,-1],::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [30]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())
print(ndata.argmin)
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
<built-in method argmin of numpy.ndarray object at 0x00000245B9058ED0>
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
